export const homeObjOne = {
    id: 'home',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: '#Truth',
    headline: 'Lorem ipsum dolor sit amet',
    description: 'Quo aliquid rerum rem omnis saepe est voluptatem rerum. Ut quia tempora ea officiis alias et maxime voluptas ea provident tempore quo dolores dolorem qui harum autem qui quia corrupti.',
    buttonLabel: 'Benchmark',
    imgStart: false,
    img: require('../../images/news.svg').default,
    alt: 'Online articles',
    dark: true,
    primary: true,
    darkText: false,
}
export const homeObjTwo = {
    id: 'search',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: '#Truth',
    headline: 'Lorem ipsum dolor sit amet',
    description: 'Quo aliquid rerum rem omnis saepe est voluptatem rerum. Ut quia tempora ea officiis alias et maxime voluptas ea provident tempore quo dolores dolorem qui harum autem qui quia corrupti.',
    buttonLabel: 'Search',
    imgStart: true,
    img: require('../../images/search.svg').default,
    alt: 'Search',
    dark: false,
    primary: false,
    darkText: true,
}
export const homeObjThree = {
    id: 'school',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: '#Truth',
    headline: 'Lorem ipsum dolor sit amet',
    description: 'Quo aliquid rerum rem omnis saepe est voluptatem rerum. Ut quia tempora ea officiis alias et maxime voluptas ea provident tempore quo dolores dolorem qui harum autem qui quia corrupti.',
    buttonLabel: 'School',
    imgStart: false,
    img: require('../../images/school.svg').default,
    alt: 'School',
    dark: true,
    primary: true,
    darkText: false,
}